### ISSUE TITLE
Addition if you don't want to have to decorate all flask funcs

### ISSUE THREAD

**Issue by utilitarianexe** [acoomans/flask-autodoc#1]
direct_decorate = auto.doc()
    for func  in app.view_functions.values():
        direct_decorate(func)

**Comment by lukeyeager** [comment]
@utilitarianexe, can you verify that this works:
```python
for endpoint, function in app.view_functions.iteritems():
    app.view_functions[endpoint] = auto.doc()(function)
```
(see more detail at #19)

**Comment by utilitarianexe** [comment]
Sorry for the late response. I do not have the code I used this on anymore because I changed companies. Would be happy to whip up some foobar code tomorrow to verify it on if that would be useful to you.

**Comment by lukeyeager** [comment]
Don't worry about it, it seems like that solution is working (see #20). I'm just trying to address all open issues. Please close this if you're satisfied.
