### ISSUE TITLE
Arguments are listed as args, kwargs when other decorators are also being used. 

### ISSUE THREAD

**Issue by sayeghr** [acoomans/flask-autodoc#11]
For example, I am using flask-basicauth and my arguments for all endpoints are:

Arguments: args  kwargs  auth  password

**Comment by lukeyeager** [comment]
Can you post the code you're using? When I do this:
```python
@app.route('/user/<int:user_id>')
@auto.doc()
@basic_auth.required
def user(user_id):
    return 'Hello, #%d!' % user_id
```
I see one argument just as I'd expect.
