### ISSUE TITLE
Fix for using groups with a custom template isn't published to pypi

### ISSUE THREAD

**Issue by barakschiller** [acoomans/flask-autodoc#13]
Hi,
Would you consider releasing the fix for using groups with a custom template to pypi?

Would also greatly appreciate the content of https://github.com/acoomans/flask-autodoc/pull/10 but the bug fix is of more importance :+1: 

Barak.

**Comment by lukeyeager** [comment]
:+1:

I also want the latest version posted to PyPI. But I want it for #8.

@acoomans, is this project still alive?

**Comment by lukeyeager** [comment]
Updated to `v0.1.2` and posted to PyPI. Thanks @acoomans!
